const personagens = [
  {
    id: '01',
    nome: 'Zhongli',
    descricao: 'Geo - Suporte - Lança',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/12/portrait-zhongli.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '02',
    nome: 'Shogun Raiden',
    descricao: 'Electro, DPS/Batery / Lança',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/09/shogun_perfil.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '03',
    nome: 'Noelle',
    descricao: 'Geo - Healer, Dps - Espadão',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-noelle.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '04',
    nome: 'Xiao',
    descricao: 'Anemo, DPS/Batery / Lança',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-xiao.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '05',
    nome: 'Tartaglia',
    descricao: 'Hydro - Dps - Arco',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-tartaglia.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '06',
    nome: 'Venti',
    descricao: 'Anemo - Suporte - Arco',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-venti.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '07',
    nome: 'Albedo',
    descricao: 'Geo, Explosão Elemental, Espada',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/12/portrait-albedo.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '08',
    nome: 'Lisa',
    descricao: 'Electro, Área de Efeito / Catalizador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-lisa.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '09',
    nome: 'Beidou 北斗',
    descricao: 'Electro - Dps - Claymore',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-beidou.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '10',
    nome: 'Viajante (Anemo)',
    descricao: 'Anemo, Suporte, Espada',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-traveler.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '11',
    nome: 'Ningguang 凝光',
    descricao: 'Geo, DPS/Suporte / Catalisador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-ningguang.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '12',
    nome: 'Ganyu 甘雨',
    descricao: 'Cryo / Dps / Arco',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/01/portrait-ganyu.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '13',
    nome: 'Jean',
    descricao: 'Anemo, DPS Healer / Espada',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-jean.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '14',
    nome: 'Klee',
    descricao: 'Pyro, DPS / Catalizador',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-klee.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '15',
    nome: 'Diluc',
    descricao: 'Pyro, DPS / Espadão',
    attr01: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr02: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    attr03: Math.floor(Math.random() * (90 - 70 + 1) + 70),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-diluc.jpg',
    raridade: 'Muito Raro',
    superT: false,
  },
  {
    id: '16',
    nome: 'Sucrose',
    descricao: 'Anemo, Suporte / Catalizador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-sucrose.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '17',
    nome: 'Chongyun  重云',
    descricao: 'Cryo, Dps / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-chongyun.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '18',
    nome: 'Diona',
    descricao: 'Cryo, Suporte / Arco',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-diona.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '19',
    nome: 'Eula',
    descricao: 'Cryo, DPS / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/05/eula-800-640.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '20',
    nome: 'Kaeya',
    descricao: 'Cryo, Suporte / Espada',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-kaeya.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '21',
    nome: 'Qiqi 七七',
    descricao: 'Cryo, Healer/Suporte / Espada',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-qiqi.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '22',
    nome: 'Fischl',
    descricao: 'Electro, DPS/Suporte / Arco',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-fischl.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '23',
    nome: 'Keqing 刻晴',
    descricao: 'Electro, DPS / Espada',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-keqing.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '24',
    nome: 'Razor',
    descricao: 'Electro, DPS / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-razor.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '25',
    nome: 'Amber',
    descricao: 'Piro, Suporte / Arco',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-amber.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '26',
    nome: 'Bennett',
    descricao: 'Pyro, DPS / Espada',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-bennett.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '27',
    nome: 'Hutao 胡桃',
    descricao: 'Pyro, DPS / Lança',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/03/portrait-hutao.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '28',
    nome: 'Xiangling 香菱',
    descricao: 'Pyro, DPS/Suporte / Lança',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-xiangling.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '29',
    nome: 'Xinyan 辛焱',
    descricao: 'Pyro, DPS / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/12/portrait-xinyan.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '30',
    nome: 'Yanfei',
    descricao: 'Pyro, DPS / Catalizador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/05/yanfei-800-600.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '31',
    nome: 'Barbara',
    descricao: 'Hydro, Healer / Catalisador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-barbara.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '32',
    nome: 'Mona',
    descricao: 'Hydro, Suporte / Catalisador',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-mona.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '33',
    nome: 'Arataki Itto',
    descricao: 'Geo, Dps / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2022/01/arataki-itto-800-600.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '34',
    nome: 'Xingqiu',
    descricao: 'Hydro, Suporte / Espadão',
    attr01: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr02: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    attr03: Math.floor(Math.random() * (80 - 60 + 1) + 60),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait-xingqiu.jpg',
    raridade: 'Raro',
    superT: false,
  },
  {
    id: '35',
    nome: 'Yunjin',
    descricao: 'Geo, Suporte / Lança',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2022/01/yunjin_Perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '36',
    nome: 'Shenhe',
    descricao: 'Cryo, Suporte / Lança',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2022/01/Shenhe-perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '37',
    nome: 'Gorou',
    descricao: 'Geo, Suporte / Arco',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2022/01/gorou.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '38',
    nome: 'Thoma',
    descricao: 'Pyro, Dps / Lança',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2022/01/thoma-perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '39',
    nome: 'Kokomi',
    descricao: 'Hydro, Sub / Dps / Catalisador',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/11/kokomi_perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '40',
    nome: 'Aloy',
    descricao: 'Cryo, Dps / Arco',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/09/Aloy_perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '41',
    nome: 'Kujou Sara',
    descricao: 'Electro, Battery / Arco',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/09/Sara_Perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '42',
    nome: 'Sayu',
    descricao: 'Anemo, Suporte / Espadão',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/08/sayu_perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '43',
    nome: 'Yoimiya',
    descricao: 'Pyro, Dps / Arco',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/08/yoimiya_perfil.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '44',
    nome: 'Ayaka',
    descricao: 'Cryo, Main Dps / Espada',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2020/11/portrait_ayaka.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '45',
    nome: 'Kazuha',
    descricao: 'Anemo, Sub Dps / Espada',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/07/kazuha-profile.jpg',
    raridade: 'Normal',
    superT: false,
  },
  {
    id: '46',
    nome: 'Rosaria',
    descricao: 'Cryo, Dps / Lança',
    attr01: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr02: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    attr03: Math.floor(Math.random() * (70 - 50 + 1) + 50),
    imagem: 'https://genshinpro.com.br/wp-content/uploads/2021/04/rosaria-800-600.jpg',
    raridade: 'Normal',
    superT: false,
  },
];

export default personagens;
